---
QUERY_URL:
  BASE_URL: https://query1.finance.yahoo.com/v1/finance/search
  QUERY: q=NIFTY&lang=en-US&region=US&quotesCount=8&newsCount=0&enableFuzzyQuery=false&quotesQueryId=tss_match_phrase_query&multiQuoteQueryId=multi_quote_single_token_query&enableCb=true&enableNavLinks=true&enableEnhancedTrivialQuery=true&enableCulturalAssets=true&enableLogoUrl=true&researchReportsCount=2

